version: '1'
services:
  redis-service:
    image: redis
    container_name: redis-service #完全控制容器的名字
    ports:
      - "6379:6379"
    depends_on: #依赖
      - redis
  
  pg-service:
    image: postgres:9.6
    container_name: pg-service
    volumes:
      - ~/Data/pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    restart: always
