version: '3'
services:
  redis-service:
    image: redis
    container_name: redis-service
    ports:
      - "6379:6379"
    depends_on:
      - redis
  
  pg-service:
    image: postgres:9.6
    container_name: pg-service
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_USER=sweet'
      - 'POSTGRES_PASSWORD=123456yy'
    volumes:
      - ~/Data/pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    restart: always
